import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import { readPageBundle } from './page-bundle.mjs';

const [pageBundle,homeBundle]=await Promise.all([readPageBundle('public/voc.html'),readPageBundle('public/index.html')]);
const paths={api:'src/voc-submission.js',worker:'src/worker.js',migration:'migrations/0009_voc_cases_v2.sql',config:'wrangler.jsonc',package:'package.json'};
const files=Object.fromEntries(await Promise.all(Object.entries(paths).map(async([key,path])=>[key,await readFile(path,'utf8')])));files.page=pageBundle.source;files.home=homeBundle.source;
function requireText(source,value,label=value){if(!source.includes(value))throw new Error(`VOC 검증 실패: ${label}`)}
for(const table of ['voc_cases_v2','voc_images_v2','voc_preview_tickets_v2','voc_case_logs_v2'])requireText(files.migration,`CREATE TABLE IF NOT EXISTS ${table}`,`${table} 테이블 누락`);
for(const status of ['draft','received','in_review','answered','closed']){requireText(files.api,`'${status}'`,`${status} API 상태 누락`);requireText(files.page,status,`${status} 화면 상태 누락`)}
for(const category of ['general','safety','facility','other'])requireText(files.api,`'${category}'`,`${category} 분류 누락`);
requireText(files.page,'id="vocContent"','내용 입력란 누락');requireText(files.page,'required placeholder=','내용 필수 표시 누락');requireText(files.api,"if (!content) return json({ success: false, error: '내용을 입력하세요.'",'서버 내용 필수검증 누락');requireText(files.api,"clean(body.title, 120) || automaticTitle(content)",'빈 제목 자동생성 누락');requireText(files.page,"navigator.clipboard?.read",'클립보드 이미지 읽기 누락');requireText(files.page,"document.addEventListener('paste'",'Ctrl+V 이미지 처리 누락');requireText(files.page,'navigator.mediaDevices?.getUserMedia','웹 카메라 처리 누락');requireText(files.page,'capture="environment"','모바일 카메라 대체입력 누락');requireText(files.page,'id="galleryPhotos"','사진함 입력 누락');requireText(files.page,'imageMinus','사진 축소 기능 누락');requireText(files.page,'imagePlus','사진 확대 기능 누락');requireText(files.api,'imageSignature','이미지 시그니처 검사 누락');requireText(files.api,'file.stream()','R2 스트리밍 업로드 누락');requireText(files.api,'MAX_CASE_IMAGES = 5','사진 수 제한 누락');requireText(files.migration,'trg_voc_images_v2_quota','동시 업로드 DB 제한 누락');requireText(files.worker,'handleVocSubmission','VOC API Worker 연결 누락');requireText(files.worker,"path==='/voc'",'VOC 페이지 Worker 경로 누락');requireText(files.config,'"/voc"','VOC Worker 우선 경로 누락');requireText(files.home,'if(service==="voc"){location.href="/voc";return}','홈 VOC 진입 연결 누락');requireText(files.package,'"verify:voc"','VOC 검증 명령 누락');
if(/사진[^\n<]{0,20}(선택사항|선택 사항)/.test(files.page))throw new Error('VOC 검증 실패: 사진 선택사항 안내 문구가 포함되어 있습니다.');if(/department|유관부서/i.test(files.api)||/department|유관부서/i.test(files.page)||/department|유관부서/i.test(files.migration))throw new Error('VOC 검증 실패: 유관부서 범위가 포함되어 있습니다.');
const ids=[...pageBundle.html.matchAll(/\sid="([^"]+)"/g)].map(match=>match[1]),duplicateIds=[...new Set(ids.filter((id,index)=>ids.indexOf(id)!==index))];if(duplicateIds.length)throw new Error(`VOC 검증 실패: 중복 DOM id (${duplicateIds.join(', ')})`);for(const script of pageBundle.scripts)new Function(script);
const db=new DatabaseSync(':memory:');db.exec(files.migration);db.prepare(`INSERT INTO voc_cases_v2 (id, company_id, category, title, content, status) VALUES ('case-1','company-1','safety','자동 제목','필수 내용','received')`).run();const row=db.prepare(`SELECT v.id,v.title,v.content,v.status,(SELECT COUNT(*) FROM voc_images_v2 i WHERE i.case_id=v.id AND i.deleted_at IS NULL) AS image_count FROM voc_cases_v2 v WHERE v.id='case-1'`).get();assert.deepEqual({...row},{id:'case-1',title:'자동 제목',content:'필수 내용',status:'received',image_count:0});assert.throws(()=>db.prepare(`INSERT INTO voc_cases_v2 (id,company_id,title,content,status) VALUES ('bad','c','t','x','invalid')`).run());for(let index=1;index<=5;index++)db.prepare(`INSERT INTO voc_images_v2 (id,case_id,object_key,file_name,content_type,file_size) VALUES (?,'case-1',?,?,'image/jpeg',100)`).run(`image-${index}`,`key-${index}`,`${index}.jpg`);assert.throws(()=>db.prepare(`INSERT INTO voc_images_v2 (id,case_id,object_key,file_name,content_type,file_size) VALUES ('image-6','case-1','key-6','6.jpg','image/jpeg',100)`).run(),/VOC_IMAGE_QUOTA_EXCEEDED/);
console.log(JSON.stringify({success:true,voc_tables:4,statuses:5,categories:4,photo_required:false,content_required:true,input_methods:['clipboard','camera','gallery'],image_zoom:true,concurrent_upload_quota:true,dom_ids:ids.length,worker_route:true,modular_page:true}));
